[package]
edition = "2018"
exclude = ["index.node"]
license = "ISC"
name = "neon-electron"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies.neon]
default-features = false
features = ["napi-6"]
version = "0.10"

[dependencies]
num_cpus = "1"
